# Generated by Django 5.1.6 on 2025-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_course_category_courselevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='advanced_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='advanced_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='advanced_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='advanced_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='beginner_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='beginner_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='beginner_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='beginner_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='foundation_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='foundation_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='foundation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='foundation_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='intermediate_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='intermediate_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='intermediate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='intermediate_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
