# Generated by Django 5.1.6 on 2025-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_delete_courselevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Foundation', 'Foundation'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100)),
                ('description', models.TextField(default='No description available')),
                ('duration', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='advanced_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='advanced_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='advanced_enabled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='advanced_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='beginner_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='beginner_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='beginner_enabled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='beginner_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='foundation_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='foundation_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='foundation_enabled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='foundation_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intermediate_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intermediate_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intermediate_enabled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intermediate_price',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.ManyToManyField(related_name='courses', to='music.level'),
        ),
    ]
