# Generated by Django 5.1.6 on 2025-04-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='highlights',
            field=models.TextField(default=''),
        ),
    ]
