# Generated by Django 5.2 on 2025-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_level_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='access',
            field=models.CharField(default='Mobile & Desktop Access', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='certificate',
            field=models.CharField(default='On completion', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='format',
            field=models.CharField(default='1:1 lesson with Teacher', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
