# Generated by Django 5.2 on 2025-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_level_access_level_certificate_level_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home_courses/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
