# Generated by Django 5.2 on 2025-04-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_course_levels_alter_course_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_levels', to='music.course'),
        ),
    ]
