# Generated by Django 5.2 on 2025-04-25 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_level_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.CharField(max_length=100, unique=True)),
                ('purchase_order_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paisa', models.IntegerField()),
                ('pidx', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('User canceled', 'User canceled'), ('Expired', 'Expired'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.level')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
