# Generated by Django 5.1.6 on 2025-04-26 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='course',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='music.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'Student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='level',
            name='highlights',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paisa',
            field=models.IntegerField(help_text='Amount in paisa (for Khalti)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='music.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='music.level'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase_order_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'profile__role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
