# Generated by Django 5.1.6 on 2025-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_notification_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='teachers/')),
            ],
        ),
        migrations.AlterField(
            model_name='level',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in Rs', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Rs', max_digits=10),
        ),
    ]
