# Generated by Django 5.1.6 on 2025-04-29 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='music.profile'),
        ),
        migrations.AddField(
            model_name='progress',
            name='profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='music.profile'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'profile__role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
