"""
Django settings for sungabha project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os  # Move this to the top
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_mo^*9332x(l$dj%xz0)uypgt*0ws16$^&xpvz1ox%wp(vgbkt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

JAZZMIN_SETTINGS = {
    "site_title": "Sungabha eMusic Academy",
    "site_header": "Sungabha eMusic Academy",
    "site_brand": "Sungabha eMusic Academy",
    "welcome_sign": "Welcome to Sungabha eMusic Academy Admin",
}

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'music',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sungabha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sungabha.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings
LOGIN_URL = 'login'  # URL name for login page (matches your login_view)
LOGIN_REDIRECT_URL = 'home'  # Redirect after login (matches your home view)
LOGOUT_REDIRECT_URL = 'login'  # Redirect after logout (matches your logout_view)

# Khalti Configuration
KHALTI_PUBLIC_KEY = "90bd2cb7db274be5b2bf86f2224396ad"  # Sandbox public key
KHALTI_SECRET_KEY = "a0b90776e78440ada0756efc2f8ade9f"  # Sandbox secret key
KHALTI_INITIATE_URL = "https://dev.khalti.com/api/v2/epayment/initiate/"  # Sandbox initiate URL
KHALTI_VERIFY_URL = "https://dev.khalti.com/api/v2/epayment/lookup/"  # Corrected to lookup endpoint

# Khalti Callback URL (replace with your actual domain)
KHALTI_RETURN_URL = "http://localhost:8000/payment-success/"  # For local testing

# Website URL (replace with your actual domain)
WEBSITE_URL = "http://localhost:8000/"  # For local testing

# Currency Conversion Rate (1 USD to NPR; adjust as needed)
USD_TO_NPR_RATE = 130  # Example: 1 USD = 130 NPR
